#! /usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

use MiraCommand\CreateModel;
use MiraCommand\CreateApp;
use MiraCommand\CreateEvent;
use MiraCommand\CreateMiddleware;
use MiraCommand\InstallApp;

require 'vendor/autoload.php';

$app = new Application('Mira Commands', '2.0');

$app->add(new CreateModel);
$app->add(new CreateApp);
$app->add(new CreateEvent);
$app->add(new CreateMiddleware);
$app->add(new InstallApp);
$app->run();

class App
{
    public static function new($input)
    {
        $created = true;
        echo "Creating app folder ... ";
        if (mkdir("application/app/$input")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app config file ... ";
        // Create config file
        if (file_put_contents("application/app/$input/config.php", "<?php

        return [
            // 'header' => '$input.base',
            // 'footer' => '$input.footer'
        ];
            ")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        // Create templates folder
        echo "Creating app template folder ... ";
        if (mkdir("application/app/$input/templates")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }
        
        // Create resources folder
        echo "Creating app images folder ... ";
        if (mkdir("application/app/$input/images")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        // Create resources folder
        echo "Creating app js folder ... ";
        if (mkdir("application/app/$input/js")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        // Create css folder
        echo "Creating app css folder ... ";
        if (mkdir("application/app/$input/css")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }


        
        echo "Creating app routes folder ... ";
        if (mkdir("application/app/$input/routes")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app routes/routes.php file ... ";
        if (fopen("application/app/$input/routes/routes.php", "a")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app controller folder ... ";
        if (mkdir("application/app/$input/controller")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app controller/controller.php file ... ";
        if (fopen("application/app/$input/controller/controller.php", "a")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app model folder ... ";
        if (mkdir("application/app/$input/models")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app models/models.php file ... ";
        if (fopen("application/app/$input/models/models.php", "a")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app middleware folder ... ";
        if (mkdir("application/app/$input/middleware")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        echo "Creating app middleware/middleware.php file ... ";
        if (fopen("application/app/$input/middleware/middleware.php", "a")) {
            echo "created successfully!\n";
        } else {
            echo "failed\n";
            $created = false;
        }

        if ($created) {
            echo "\nApp Successfully Created!";
        } else {
            echo "\nApp could not be created ...";
        }
    }
}

class Model
{
    public static function new($model, $database)
    {
        echo "Creating model ... ";
        $file = fopen("application/models/models.php", "a");

        if ($database) {
            $database_text = "\n\tprotected ".'$db'." = '$database';\n";
        }

        fwrite($file, "\nclass $model extends Model".'{'."$database_text".'}'."\n");

        fclose($file);
        echo "created successfully\n";
    }
}
