#! /usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

use MiraCommand\CreateModel;
use MiraCommand\CreateTest;
use MiraCommand\CreateApp;
use MiraCommand\CreateEvent;
use MiraCommand\CreateMiddleware;
use MiraCommand\InstallApp;

require 'vendor/autoload.php';

$app = new Application('Mira Commands', '2.0');

$app->add(new CreateModel);
$app->add(new CreateApp);
$app->add(new CreateEvent);
$app->add(new CreateMiddleware);
$app->add(new InstallApp);
$app->add(new CreateTest);
$app->run();
